"""GitHub integration service: PR description builder and PR creation."""

from __future__ import annotations

import asyncio


def build_pr_description(
    task: dict,
    subtasks: list[dict],
    review_results: dict | None = None,
) -> str:
    """Build a markdown PR description from task info.

    Args:
        task: Main task dict with 'description' key.
        subtasks: List of subtask dicts, each with 'id', 'description', 'status'.
        review_results: Optional review gate results dict with 'passed' and 'summary'.

    Returns:
        Markdown-formatted PR description string.
    """
    lines: list[str] = []

    # Task description
    lines.append("## Description")
    lines.append("")
    lines.append(task.get("description", "No description provided."))
    lines.append("")

    # Subtask summary table
    if subtasks:
        lines.append("## Subtasks")
        lines.append("")
        lines.append("| # | Description | Status |")
        lines.append("|---|-------------|--------|")
        for i, st in enumerate(subtasks, 1):
            status_emoji = "pass" if st.get("status") == "complete" else st.get("status", "pending")
            lines.append(f"| {i} | {st.get('description', '')} | {status_emoji} |")
        lines.append("")

    # Review gate results
    if review_results:
        lines.append("## Review Gate")
        lines.append("")
        passed = review_results.get("passed", False)
        lines.append(f"**Result:** {'Passed' if passed else 'Failed'}")
        if review_results.get("summary"):
            lines.append("")
            lines.append(review_results["summary"])
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by [Forge Orchestrator](https://github.com/tarunms7/forge-orchestrator)*")

    return "\n".join(lines)


async def create_pr(
    repo_path: str,
    branch: str,
    title: str,
    body: str,
) -> dict:
    """Create a GitHub PR using the ``gh`` CLI.

    Args:
        repo_path: Local path to the git repository.
        branch: Branch name to create PR from.
        title: PR title.
        body: PR body (markdown).

    Returns:
        Dict with ``url`` and ``number`` keys.

    Raises:
        RuntimeError: If the ``gh`` command fails.
    """
    proc = await asyncio.create_subprocess_exec(
        "gh", "pr", "create",
        "--title", title,
        "--body", body,
        "--head", branch,
        cwd=repo_path,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        raise RuntimeError(f"gh pr create failed: {stderr.decode().strip()}")

    url = stdout.decode().strip()

    # Extract PR number from URL (e.g., https://github.com/owner/repo/pull/42)
    number = 0
    parts = url.rstrip("/").split("/")
    if parts:
        try:
            number = int(parts[-1])
        except ValueError:
            pass

    return {"url": url, "number": number}
